/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.Serializable;
import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author Alpha
 */
public class EditStudent extends javax.swing.JDialog implements Serializable {
    private MainFrame mainFrame;

    public void setStudent(Student student) {
        this.student = student;
    }

    private Student student;
    private String[] groupList = {"Language & Art", "Math", "STEM"};
    /**
     * Creates new form EditStudent
     */
    public EditStudent(MainFrame m, Student s) {
        this.mainFrame = m;
        this.student = s;
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setModalityType(ModalityType.APPLICATION_MODAL);
        setResizable(false);
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studentNameTextField = new javax.swing.JTextField();
        groupComboBox = new javax.swing.JComboBox<>();
        courseComboBox = new javax.swing.JComboBox<>();
        doneButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Student");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Group:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Course:");

        studentNameTextField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        groupComboBox.setMaximumRowCount(20);
        groupComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(groupList)
        );
        groupComboBox.setSelectedItem(this.student.getGroup());
        groupComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupComboBoxActionPerformed(evt);
            }
        });

        String group = this.student.getGroup();
        if (group == "Math") {
            courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(mainFrame.getMathList()));
        }   else if (group == "STEM") {
            courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(mainFrame.getStemList()));
        }
        else if (group == "Language & Art")
        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(mainFrame.getLanguageArtList()));
        courseComboBox.setSelectedItem(this.student.getCourse());

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(courseComboBox, 0, 223, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(groupComboBox, 0, 223, Short.MAX_VALUE)
                                .addComponent(studentNameTextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(groupComboBox)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(courseComboBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        studentNameTextField.setText(this.student.getName());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        String name = this.studentNameTextField.getText().toString();
        String group = this.groupComboBox.getSelectedItem().toString();
        String course = this.courseComboBox.getSelectedItem().toString();

        if (this.student.getName() == name && this.student.getCourse() == course && this.student.getGroup() == group) {
            this.setVisible(false);
            return;
        }

        if (this.student.getGroup() == group) {
            this.student.setName(name);
            this.student.setCourse(course);
            if (group.equals("Language & Art")) {
                this.mainFrame.updateTable(this.mainFrame.getLanguageArtTable(), this.mainFrame.getData().getLanguageArtStudent());
            } else if (group.equals("Math")) {
                this.mainFrame.updateTable(this.mainFrame.getMathTable(), this.mainFrame.getData().getMathStudent());
            } else if (group.equals("STEM")) {
                this.mainFrame.updateTable(this.mainFrame.getStemTable(), this.mainFrame.getData().getStemStudent());
            }
        } else {
            this.mainFrame.delete(0);
            Student student = new Student(name, group, course);
            boolean found = false;
            for (int i = 0; !found && i < this.mainFrame.getLanguageArtList().length; i++) {
                if (this.mainFrame.getLanguageArtList()[i].equals(course)) {
                    found = true;
                    student.setGroup("Language & Art");
                    this.mainFrame.getData().getLanguageArtStudent().add(student);
                    this.mainFrame.updateTable(this.mainFrame.getLanguageArtTable(), this.mainFrame.getData().getLanguageArtStudent());
                }
            }
            for (int i = 0; !found && i < this.mainFrame.getMathList().length; i++) {
                if (this.mainFrame.getMathList()[i].equals(course)) {
                    found = true;
                    student.setGroup("Math");
                    this.mainFrame.getData().getMathStudent().add(student);
                    this.mainFrame.updateTable(this.mainFrame.getMathTable(), this.mainFrame.getData().getMathStudent());
                }
            }
            for (int i = 0; !found && i < this.mainFrame.getStemList().length; i++) {
                if (this.mainFrame.getStemList()[i].equals(course)) {
                    found = true;
                    student.setGroup("STEM");
                    this.mainFrame.getData().getStemStudent().add(student);
                    this.mainFrame.updateTable(this.mainFrame.getStemTable(), this.mainFrame.getData().getStemStudent());
                }
            }
        }

        this.setVisible(false);
    }//GEN-LAST:event_doneButtonActionPerformed

    private void groupComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupComboBoxActionPerformed
        // TODO add your handling code here:
        String s = this.groupComboBox.getSelectedItem().toString();
        if (!s.equals(this.student.getName())) {
            if (s.equals("Language & Art")) {
                courseComboBox.setModel(new DefaultComboBoxModel<>(mainFrame.getLanguageArtList()));
            } else if (s.equals("Math")) {
                courseComboBox.setModel(new DefaultComboBoxModel<>(mainFrame.getMathList()));
            } else if (s.equals("STEM")) {
                courseComboBox.setModel(new DefaultComboBoxModel<>(mainFrame.getStemList()));
            }
        }
    }//GEN-LAST:event_groupComboBoxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    public void display(boolean visible) {
        studentNameTextField.setText(this.student.getName());
        groupComboBox.setSelectedItem(this.student.getGroup());
        String group = this.student.getGroup();
        if (group == "Math") {
            courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(mainFrame.getMathList()));
        }   else if (group == "STEM") {
            courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(mainFrame.getStemList()));
        }
        else if (group == "Language & Art")
            courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(mainFrame.getLanguageArtList()));
        courseComboBox.setSelectedItem(this.student.getCourse());
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JButton doneButton;
    private javax.swing.JComboBox<String> groupComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField studentNameTextField;
    // End of variables declaration//GEN-END:variables
}
